### ISSUE TITLE
dat:// protocol urls are opening in Beaker

### ISSUE THREAD

**Issue by jamesgecko** [sammacbeth/dat-fox-helper#6]
I ran the setup script on MacOS, and the extension test passes. But when I click on a `dat://` link in Firefox, a blank tab opens with the URL. Then the page is opened in Beaker Browser.

**Comment by jamesgecko** [comment]
Nevermind; I figured it out.

<img width="879" alt="screen shot 2019-02-08 at 11 12 54 am" src="https://user-images.githubusercontent.com/44252/52490348-8bab7500-2b92-11e9-9595-2703b97ac444.png">

**Comment by masukomi** [comment]
I almost filed this exact same issue. Can we please get an addition to the setup page that instructs users where and how to do this? It was not obvious.

**Comment by sammacbeth** [comment]
Yes, this information could be added in https://github.com/sammacbeth/dat-fox/blob/master/addon/pages/setup.html
